//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop_netframework472
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookExemplar
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Status Status { get; set; }
        public virtual Order Order { get; set; }
    }
}
